/*
 * Basin RPC API
 *
 * Basin RPC API
 *
 * API version: 1.0.11
 * Contact: sestinj@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type NotifyRequest struct {

	Url string `json:"url"`
}

// AssertNotifyRequestRequired checks if the required fields are not zero-ed
func AssertNotifyRequestRequired(obj NotifyRequest) error {
	elements := map[string]interface{}{
		"url": obj.Url,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseNotifyRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NotifyRequest (e.g. [][]NotifyRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNotifyRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNotifyRequest, ok := obj.(NotifyRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNotifyRequestRequired(aNotifyRequest)
	})
}
