/*
 * Basin RPC API
 *
 * Basin RPC API
 *
 * API version: 1.0.11
 * Contact: sestinj@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type AdapterSchema struct {

	AdapterName string `json:"adapterName"`

	Config map[string]interface{} `json:"config"`
}

// AssertAdapterSchemaRequired checks if the required fields are not zero-ed
func AssertAdapterSchemaRequired(obj AdapterSchema) error {
	elements := map[string]interface{}{
		"adapterName": obj.AdapterName,
		"config": obj.Config,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAdapterSchemaRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AdapterSchema (e.g. [][]AdapterSchema), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAdapterSchemaRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAdapterSchema, ok := obj.(AdapterSchema)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAdapterSchemaRequired(aAdapterSchema)
	})
}
