/*
 * Basin RPC API
 *
 * Basin RPC API
 *
 * API version: 1.0.11
 * Contact: sestinj@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type AdapterJson struct {

	AdapterName string `json:"adapterName"`

	Config map[string]interface{} `json:"config"`
}

// AssertAdapterJsonRequired checks if the required fields are not zero-ed
func AssertAdapterJsonRequired(obj AdapterJson) error {
	elements := map[string]interface{}{
		"adapterName": obj.AdapterName,
		"config": obj.Config,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAdapterJsonRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of AdapterJson (e.g. [][]AdapterJson), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAdapterJsonRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAdapterJson, ok := obj.(AdapterJson)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAdapterJsonRequired(aAdapterJson)
	})
}
