/*
Basin RPC API

Basin RPC API

API version: 1.0.11
Contact: sestinj@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// PermissionSchema struct for PermissionSchema
type PermissionSchema struct {
	Data []string `json:"data,omitempty"`
	Capabilities []CapabilitySchema `json:"capabilities,omitempty"`
	Entities []string `json:"entities,omitempty"`
}

// NewPermissionSchema instantiates a new PermissionSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionSchema() *PermissionSchema {
	this := PermissionSchema{}
	return &this
}

// NewPermissionSchemaWithDefaults instantiates a new PermissionSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionSchemaWithDefaults() *PermissionSchema {
	this := PermissionSchema{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *PermissionSchema) GetData() []string {
	if o == nil || o.Data == nil {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSchema) GetDataOk() ([]string, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *PermissionSchema) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *PermissionSchema) SetData(v []string) {
	o.Data = v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *PermissionSchema) GetCapabilities() []CapabilitySchema {
	if o == nil || o.Capabilities == nil {
		var ret []CapabilitySchema
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSchema) GetCapabilitiesOk() ([]CapabilitySchema, bool) {
	if o == nil || o.Capabilities == nil {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *PermissionSchema) HasCapabilities() bool {
	if o != nil && o.Capabilities != nil {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []CapabilitySchema and assigns it to the Capabilities field.
func (o *PermissionSchema) SetCapabilities(v []CapabilitySchema) {
	o.Capabilities = v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *PermissionSchema) GetEntities() []string {
	if o == nil || o.Entities == nil {
		var ret []string
		return ret
	}
	return o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionSchema) GetEntitiesOk() ([]string, bool) {
	if o == nil || o.Entities == nil {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *PermissionSchema) HasEntities() bool {
	if o != nil && o.Entities != nil {
		return true
	}

	return false
}

// SetEntities gets a reference to the given []string and assigns it to the Entities field.
func (o *PermissionSchema) SetEntities(v []string) {
	o.Entities = v
}

func (o PermissionSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Capabilities != nil {
		toSerialize["capabilities"] = o.Capabilities
	}
	if o.Entities != nil {
		toSerialize["entities"] = o.Entities
	}
	return json.Marshal(toSerialize)
}

type NullablePermissionSchema struct {
	value *PermissionSchema
	isSet bool
}

func (v NullablePermissionSchema) Get() *PermissionSchema {
	return v.value
}

func (v *NullablePermissionSchema) Set(val *PermissionSchema) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionSchema) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionSchema(val *PermissionSchema) *NullablePermissionSchema {
	return &NullablePermissionSchema{value: val, isSet: true}
}

func (v NullablePermissionSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


