/*
Basin RPC API

Basin RPC API

API version: 1.0.11
Contact: sestinj@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// AdapterJson struct for AdapterJson
type AdapterJson struct {
	AdapterName string `json:"adapterName"`
	Config map[string]interface{} `json:"config"`
}

// NewAdapterJson instantiates a new AdapterJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdapterJson(adapterName string, config map[string]interface{}) *AdapterJson {
	this := AdapterJson{}
	this.AdapterName = adapterName
	this.Config = config
	return &this
}

// NewAdapterJsonWithDefaults instantiates a new AdapterJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdapterJsonWithDefaults() *AdapterJson {
	this := AdapterJson{}
	return &this
}

// GetAdapterName returns the AdapterName field value
func (o *AdapterJson) GetAdapterName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdapterName
}

// GetAdapterNameOk returns a tuple with the AdapterName field value
// and a boolean to check if the value has been set.
func (o *AdapterJson) GetAdapterNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdapterName, true
}

// SetAdapterName sets field value
func (o *AdapterJson) SetAdapterName(v string) {
	o.AdapterName = v
}

// GetConfig returns the Config field value
func (o *AdapterJson) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *AdapterJson) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *AdapterJson) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o AdapterJson) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["adapterName"] = o.AdapterName
	}
	if true {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableAdapterJson struct {
	value *AdapterJson
	isSet bool
}

func (v NullableAdapterJson) Get() *AdapterJson {
	return v.value
}

func (v *NullableAdapterJson) Set(val *AdapterJson) {
	v.value = val
	v.isSet = true
}

func (v NullableAdapterJson) IsSet() bool {
	return v.isSet
}

func (v *NullableAdapterJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdapterJson(val *AdapterJson) *NullableAdapterJson {
	return &NullableAdapterJson{value: val, isSet: true}
}

func (v NullableAdapterJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdapterJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


